[tool.poetry]
name = "notifications-admin"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
ago = "~=0.0.95"
beautifulsoup4 = "^4.12.3"
boto3 = "^1.28.66"
botocore = "^1.31.66"
deptry = "==0.8.0"
eventlet = "==0.24.1"
flask = "~=2.3"
flask-login = "^0.6"
flask-talisman = "*"
flask-wtf = "^1.2"
gunicorn = {version = "==21.2.0", extras = ["eventlet"]}
humanize = "~=4.9"
itsdangerous = "~=2.1"
jinja2 = "~=3.1"
markdown = "^3.5.2"
markupsafe = "^2.1.2"
newrelic = "*"
notifications-python-client = "==8.2.0"
notifications-utils = {git = "https://github.com/GSA/notifications-utils.git"}
orderedset = "^2.0.3"
pyexcel = "==0.7.0"
pyexcel-io = "==0.6.6"
pyexcel-ods3 = "==0.6.1"
pyexcel-xls = "==0.7.0"
pyexcel-xlsx = "==0.6.0"
python-dotenv = "==1.0.1"
pytz = "==2023.3.post1"
redis = "^5.0.1"
requests = "^2.31.0"
werkzeug = "^3.0.1"
wtforms = "~=3.1"
xlrd = "==2.0.1"


[tool.poetry.group.dev.dependencies]
bandit = "*"
black = "^23.12.1"
coverage = "*"
freezegun = "^1.4.0"
flake8 = "^6.1.0"
flake8-bugbear = "^24.1.17"
flake8-print = "^5.0.0"
flake8-pytest-style = "^1.7.2"
isort = "^5.13.2"
jinja2-cli = {version = "==0.8.2", extras = ["yaml"]}
moto = "^4.2"
pip-audit = "*"
pre-commit = "^3.6.0"
pytest = "^7.4.4"
pytest-env = "^1.1.3"
pytest-mock = "^3.12.0"
pytest-playwright = "^0.4.3"
pytest-xdist = "^3.5.0"
radon = "^6.0.1"
requests-mock = "^1.11.0"
vulture = "^2.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
