[tool.poetry]
name = "notifications-admin"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
axe-core-python = "^0.1.0"
python = "^3.12.2"
ago = "~=0.0.95"
beautifulsoup4 = "^4.13.3"
blinker = "~=1.8"
exceptiongroup = "==1.2.2"
flask = "~=3.0"
flask-basicauth = "~=0.2"
flask-login = "^0.6"
flask-talisman = "*"
flask-wtf = "^1.2"
gunicorn = {version = "==23.0.0", extras = ["eventlet"]}
humanize = "~=4.12"
itsdangerous = "~=2.2"
jinja2 = "^3.1.6"
newrelic = "*"
notifications-python-client = "==10.0.1"
pyexcel = "==0.7.2"
pyexcel-io = "==0.6.7"
pyexcel-ods3 = "==0.6.1"
pyexcel-xls = "==0.7.1"
pyexcel-xlsx = "==0.6.1"
openpyxl = "==3.0.10"
pyproj = "==3.7.1"
python-dotenv = "==1.1.0"
pytz = "^2025.2"
rtreelib = "==0.2.0"
werkzeug = "^3.1.3"
wtforms = "~=3.1"
markdown = "^3.7"
mistune = "^3.1.3"
async-timeout = "^4.0.3"
bleach = "^6.1.0"
boto3 = "^1.35.99"
botocore = "^1.35.99"
cachetools = "^5.5.2"
cffi = "^1.16.0"
cryptography = "^44.0.2"
flask-redis = "^0.4.0"
geojson = "^3.1.0"
jmespath = "^1.0.1"
numpy = "^2.2.4"
ordered-set = "^4.1.0"
phonenumbers = "^9.0.2"
pycparser = "^2.22"
python-json-logger = "^3.3.0"
redis = "^5.2.1"
regex = "^2024.11.6"
s3transfer = "^0.10.2"
shapely = "^2.0.5"
smartypants = "^2.0.1"
certifi = "^2025.1.31"
charset-normalizer = "^3.4.1"
click = "^8.1.8"
idna = "^3.7"
markupsafe = "^2.1.5"
python-dateutil = "^2.9.0.post0"
pyyaml = "^6.0.1"
requests = "^2.32.3"
six = "^1.16.0"
urllib3 = "^2.2.2"
webencodings = "^0.5.1"


[tool.poetry.group.dev.dependencies]
awscli = "^1.34.29"
bandit = "*"
black = "^25.1.0"
coverage = "*"
detect-secrets = "^1.5.0"
freezegun = "^1.5.1"
flake8 = "^7.1.2"
flake8-bugbear = "^24.12.12"
flake8-print = "^5.0.0"
flake8-pytest-style = "^2.1.0"
isort = "^6.0.1"
jinja2-cli = {version = "==0.8.2", extras = ["yaml"]}
moto = "*"
pip-audit = "*"
pre-commit = "^4.2.0"
pytest = "^8.3.2"
pytest-env = "^1.1.3"
pytest-mock = "^3.14.0"
pytest-playwright = "^0.7.0"
pytest-xdist = "^3.5.0"
radon = "^6.0.1"
requests-mock = "^1.11.0"
vulture = "^2.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
